services:

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - '../.env'
    networks:
      - tibia
    ports:
      - "3306:3306"
    volumes:
      - 'database:/var/lib/mysql'
      - './schema.sql:/docker-entrypoint-initdb.d/init.sql'
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    env_file:
      - '../.env'
    networks:
      - tibia
    ports:
      - 5001:80
    depends_on:
      - database
      
  website:
    container_name: website
    ports:
      - 5000:80
    build:
      args:
        user: www-data
        uid: 33
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    env_file:
      - '../.env'
    networks:
      - tibia
    depends_on:
      - database
      - phpmyadmin

  server:
    container_name: server
    image: ghcr.io/tibia-oce/server:latest
    restart: always
    ports:
      - 7171:7171
      - 7172:7172
    networks:
      - tibia
    depends_on:
      - database
      - website
      - phpmyadmin
    env_file:
      - '../.env'

volumes:
  database:

networks:
  tibia:
    driver: bridge
